# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Prototune_data_preparation',
                'doc_host': 'https://fevzikilas.github.io',
                'git_url': 'https://github.com/fevzikilas/Prototune_data_preparation',
                'lib_path': 'Prototune_data_preparation'},
  'syms': { 'Prototune_data_preparation.core': { 'Prototune_data_preparation.core.foo': ( 'core.html#foo',
                                                                                          'Prototune_data_preparation/core.py')}}}
